name: 'Evalogik Z-Wave Dimmer'
packageKey: 'zwave-switch'
permissions:
  zwave: {}
description: "Customized SmartThings driver for Evalogik Z-Wave dimmer devices"
vendorSupportInformation: "https://support.smartthings.com"
